config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'help' => 'static_pages#help'
  get 'contact' => 'static_pages#contact'
  get 'terms' => 'static_pages#terms'
  post 'dashboard' => 'static_pages#dashboard'
  get 'dashboard' => 'static_pages#dashboard'
  # twitter
  post 'twitter_follow' => 'twitter_follows#follow'
  post 'twitter_summary' => 'twitter_follows#post_tweet'
  post 'twitter_retweet' => 'twitter_follows#retweet'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_acquisition.rb
class UserAcquisition < ActiveRecord::Base
  def create
  end

client = Twitter::REST::Client.new do |config|
   config.consumer_key        = "nVm66LX4gtPp3BQxznYIpYQ6c"
   config.consumer_secret     = "iI6rLxbYliTPkqMWN1fuNgzKcg5H62Lhq7hTwXiPBfmfm4mAjw"
   config.access_token        = "741710243311149056-AXKreZc0zJ58K0BXZNlgstB2sHd7nsx"
   config.access_token_secret = "979VeZvUbPjbCkugMAA3HKAM62iEJ37bO3fJI2YuJZa7S"
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about
  end

  def help
  end

  def contact
  end

  def terms
  end
end

app/controllers/twitter_connections_controller.rb
class TwitterConnectionsController < ApplicationController
end

app/controllers/twitter_follows_controller.rb
class TwitterFollowsController < ApplicationController
  require 'CSV'

  def follow
    now = Time.now.to_s.split(" ")[0..1].join("-")
    script = Rails.root.join("lib", "external_scripts", "autovir.R")
    data = Rails.root.join("data")
    hashtag = params[:hashtag]
    recommended_csv = data + (now+"recommendations.csv")
    output = `Rscript #{script} "#{hashtag}"  "AutovirCo" "#{recommended_csv}" '#{data+(now+"scrape.csv")}' '#{data+(now+"summary.csv")}' '#{data+(now+"followers.csv")}'`
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = "nVm66LX4gtPp3BQxznYIpYQ6c"
      config.consumer_secret     = "iI6rLxbYliTPkqMWN1fuNgzKcg5H62Lhq7hTwXiPBfmfm4mAjw"
      config.access_token        = "741710243311149056-AXKreZc0zJ58K0BXZNlgstB2sHd7nsx"
      config.access_token_secret = "979VeZvUbPjbCkugMAA3HKAM62iEJ37bO3fJI2YuJZa7S"
    end
    begin
      CSV.foreach(recommended_csv) do |row|
        client.follow(row[0])
      end
    rescue Twitter::Error::TooManyRequests => error
      flash[:error] = "Twitter rate limit"
    end
    flash[:success] = "Succesfully followed Twitter accounts!"
    redirect_to dashboard_url
  end

  def post_tweet
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = "nVm66LX4gtPp3BQxznYIpYQ6c"
      config.consumer_secret     = "iI6rLxbYliTPkqMWN1fuNgzKcg5H62Lhq7hTwXiPBfmfm4mAjw"
      config.access_token        = "741710243311149056-AXKreZc0zJ58K0BXZNlgstB2sHd7nsx"
      config.access_token_secret = "979VeZvUbPjbCkugMAA3HKAM62iEJ37bO3fJI2YuJZa7S"
    end
    r = ConceptExtraction.new(params[:link]).analyze
    tweet = r["positive"][0..2].map { |x| x["original_text"] }.join("...") + " "
    tweet += r["positive"][0..2].map { |x| "#" + x["sentiment"].tr(" ", "") }.join(" ")
    client.update(tweet[0..139])
    flash[:success] = "The tweet has been succesfully posted: #{tweet}"
    redirect_to dashboard_url
  end

  def retweet
    now = Time.now.to_s.split(" ")[0..1].join("-")
    script = Rails.root.join("lib", "external_scripts", "autovir2.R")
    data = Rails.root.join("data")
    hashtag = params[:retweet]
    recommended_csv = data + (now+"retweet_list.csv")
    output = `Rscript #{script} "#{hashtag}"  "AutovirCo" "#{recommended_csv}" '#{data+(now+"sentiment.csv")}'`
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = "nVm66LX4gtPp3BQxznYIpYQ6c"
      config.consumer_secret     = "iI6rLxbYliTPkqMWN1fuNgzKcg5H62Lhq7hTwXiPBfmfm4mAjw"
      config.access_token        = "741710243311149056-AXKreZc0zJ58K0BXZNlgstB2sHd7nsx"
      config.access_token_secret = "979VeZvUbPjbCkugMAA3HKAM62iEJ37bO3fJI2YuJZa7S"
    end
    begin
      CSV.foreach(recommended_csv) do |row|
        client.retweet(row[0])
      end
    rescue Twitter::Error::TooManyRequests => error
      flash[:error] = "Twitter rate limit"
      redirect_to dashboard_url
    end
    flash[:success] = "succesfully retweeted!"
    redirect_to dashboard_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instagram_connections_helper.rb
module InstagramConnectionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_acquisitions_helper.rb
module UserAcquisitionsHelper
end

app/views/layouts/_footer.html.erb
<nav class="downthis">
<nav class="navbar navbar-default navbar-bottom" class=role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-footer">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "About", "/about" %></li>
          <li><%= link_to "Contact", "/contact" %></li>
          <li><%= link_to "Help", "/help" %></li>
          <li><%= link_to "Terms and Conditions", "/terms" %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "autovir", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="glyphicon glyphicon-user"></i><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Edit Profile</a></li>
              <li><a href="#">Accounts</a></li>
              <li><a href="#">Settings</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
      <% if user_signed_in? %>
        <form class="navbar-form navbar-right" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Autovir</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= favicon_link_tag 'favicon.png' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container main">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/static_pages/about.html.erb
<h1>about</h1>
<p>autovir is an automated social media analyst.</p>

app/views/static_pages/contact.html.erb
<h1>contact</h1>
<p>call us at 1 800-autovir.</p>

app/views/static_pages/dashboard.html.erb
<div class="text-center">
<h1 class="text-left remove-margin">Dashboard</h1>
</div>

<div class="col-md-6 col-lg-6">
  <%= form_tag(twitter_follow_path, method: "post") do %>
    <%= label_tag(:hashtag, "Follow users", class: "btn-block") %>
    <%= text_field_tag :hashtag, nil,placeholder: "#hashtag", class: 'form-control max-form btn-inline' %>
    <%= button_tag type: 'submit', class: "btn btn-info btn-inline" do %>
      Follow
    <% end %>
  <% end %>
  
  <%= form_tag(twitter_summary_path, method: "post") do %>
    <%= label_tag(:link, "Summarize and tweet webpage", class: "btn-block") %>
    <%= text_field_tag :link, nil, placeholder: "url", class: 'form-control max-form btn-inline' %>
    <%= button_tag type: 'submit', class: "btn btn-info btn-inline" do %>
      Summarize
    <% end %>
  <% end %>

  <%= form_tag(twitter_retweet_path, method: "post") do %>
    <%= label_tag(:retweet, "Summarize and tweet webpage", class: "btn-block") %>
    <%= text_field_tag :retweet, nil, placeholder: "#hashtag", class: 'form-control max-form btn-inline' %>
    <%= button_tag type: 'submit', class: "btn btn-info btn-inline" do %>
      Retweet
    <% end %>
  <% end %>
</div>

</div>
<div class="text-center">
<iframe width="370" height="400" frameborder="0" scrolling="no" src="https://plot.ly/~mccurdys/5.embed"></iframe>
<iframe width="370" height="400" frameborder="0" scrolling="no" src="https://plot.ly/~mccurdys/3.embed"></iframe>
<iframe width="370" height="400" frameborder="0" scrolling="no" src="https://plot.ly/~mccurdys/7.embed"></iframe>
</div>

app/views/static_pages/help.html.erb
<h1>help</h1>
<p>why don't you google it?</p>

app/views/static_pages/home.html.erb
<div class="text-center">
  <% if user_signed_in? %>
    <%= image_tag 'logo.svg', class:"logo-ting" %>
    <%= image_tag 'plus.png', class:"plus" %>
    <%= image_tag 'twitter.svg', class:"twitter-logo" %>
    <br>
    <br>
    <br>
    <%= link_to 'Connect to Twitter',dashboard_path, class: 'myButton' %>
  <% else %>
    <%= image_tag 'logo.svg', class:"logo-org" %>
  <% end %>
</div>

app/views/static_pages/terms.html.erb
<h1>terms</h1>
<p>if you sign up with us then we own your soul.</p>